language: php
sudo: false

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then PHPUNIT_FLAGS="--coverage-clover ./clover.xml"; else PHPUNIT_FLAGS=""; fi
  - composer update

script:
  - make analyze-ci
  - make test
  - if php -i |grep -qE xdebug; then make infection; fi

matrix:
  allow_failures:
  - php: nightly
