language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update

script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then make analyze-ci; fi
  - make test
  - if php -m |grep -qE xdebug; then make infection; fi

matrix:
  allow_failures:
  - php: nightly
